/**:
  ros__parameters:
    road_xml: 
      /home/christiaan/thesis/robot_ws/install/foresee_the_unseen/share/foresee_the_unseen/resource/road_xmls/road_4way_50cm_6cm.xml

/fov_node:
  ros__parameters:
    # maximum inclination angle lidar
    max_inclination_angle: 1.2173 # 1.2173 rad == 70 deg

    # lidar error models z-values
    apply_errors_models: true
    range_stds_margin: 2.0
    angle_stds_margin: 2.0
    # fov state uncertainty z-values
    do_correct_state_uncertainty: true
    state_pos_stds_margin: 2.0
    state_orient_stds_margin: 2.0

    # Lidar view range
    view_range: 5.0
    # Lidar subsample rate
    subsample_rate: 5
    # Filter the pointcloud measurements
    do_filter_scan: false

/scan_simulate_node:
  ros__parameters:
    do_filter_scan: true
    # environment_boundary: [-0.01, 0.01, 0.01, 0.01, 0.01, -0.01, -0.01, -0.01]
    # environment_boundary: [-5.3, -0.5, -5.3, 0.5, -0.5, 3.0, 0.5, 3.0, 5.3, 0.5, 5.3, -0.5, 0.5, -1.5, -0.5, -1.5]
    environment_boundary:
    - -5.3
    - -0.5
    - -5.3
    - 0.5
    - -0.5
    - 1.0
    - 0.5
    - 1.0
    - 5.3
    - 0.5
    - 5.3
    - -0.5
    - 0.5
    - -1.5
    - -0.5
    - -1.5
    namespaces:
    - a
