/planner_node:
  ros__parameters:
    road_xml: /home/christiaan/thesis/robot_ws/install/foresee_the_unseen/share/foresee_the_unseen/resource/road_3way_50cm.xml

/fov_node:
  ros__parameters:
    # maximum inclination angle lidar
    max_inclination_angle: 1.2173 # 1.2173 rad == 70 deg

    # lidar error models z-values
    apply_errors_models: True
    range_stds_margin: 2.
    angle_stds_margin: 2.
    # fov state uncertainty z-values
    do_correct_state_uncertainty: True
    state_pos_stds_margin: 2.
    state_orient_stds_margin: 2.

    # Lidar view range
    view_range: 5.
    # Lidar subsample rate
    subsample_rate: 5
    # Filter the pointcloud measurements
    do_filter_scan: True
    # environment_boundary: [0., 2.5, 5., 2.5, 5., -3., 0., -3.]
    environment_boundary: [-5., 5., 5., 5., 5., -5., -5., -5.]
