my_ekf_filter_node:
    ros__parameters:
        frequency: 10.0
        sensor_timeout: 0.5 # not sure about this one
        publish_tf: true
        two_d_mode: true
        print_diagnostics: true
        permit_corrected_publication: false # not sure about this one
        #reset_on_time_jump: true
        map_frame: map               
        odom_frame: odom                 
        base_link_frame: base_link  
        world_frame: odom # So it provides the filtered pose of the base_link frame in the odom frame
   
        odom0: /odom
        odom0_config: [true, true, false,
                    false, false, true,
                    false, false, false,
                    false, false, false,
                    false, false, false]
        odom0_queue_size: 2
        odom0_differential: false
        # odom0_relative: false
        odom0_pose_rejection_threshold: 5.0
        odom0_twist_rejection_threshold: 1.0

        imu0: /imu_data
        imu0_config: [false, false, false,
                     false, false, true,
                     false, false, false,
                     true, true, true,
                     true, true, true]

        imu0_nodelay: false
        imu0_differential: false
        imu0_relative: true
        imu0_queue_size: 7
        imu0_pose_rejection_threshold: 0.8             
        imu0_twist_rejection_threshold: 0.8                
        imu0_linear_acceleration_rejection_threshold: 0.8  

        # process_noise_covariance: [0.1, 0.1, 0.1, 0.1, 0.1, 0.1, 0.1, 0.1, 0.1, 0.1, 0.1, 0.1, 0.1, 0.1, 0.1]
        process_noise_covariance: [0.01, 0.01, 0.01, 0.01, 0.01, 0.01, 0.01, 0.01, 0.01, 0.01, 0.01, 0.01, 0.01, 0.01, 0.01]
        # initial_estimate_covariance: [1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.]
        initial_estimate_covariance: [0.1, 0.1, 0.1, 0.1, 0.1, 0.1, 0.1, 0.1, 0.1, 0.1, 0.1, 0.1, 0.1, 0.1, 0.1]
