planner_node:
  ros__parameters:
    map_frame: map
    base_frame: base_link
    lidar_frame: laser
    planner_frame: planner

    lidar_topic: scan 
    odom_topic: odometry/filtered
    datmo_topic: datmo/box_kf 
    filtered_lidar_topic: scan/road_env
    visualization_topic: visualization/planner
    
    environment_boundary: [0., 2.5, 5., 2.5, 5., -3., 0., -3.]  # CW convex polygon [x1, y1, x2, y2, ...] in the map frame
    
    ego_vehicle_size: [0.25, 0.18, 0.12]
    ego_vehicle_offset: [0., 0., 0.06]
    planner_frequency: 4. # [Hz]

    # use_triangulation: True
    num_pred_to_visualize: 5
    # do_visualize: True
    
    # road_xml: /home/christiaan/thesis/robot_ws/install/foresee_the_unseen/share/foresee_the_unseen/resource/road_structure.xml




