/visualization_node:
  ros__parameters:
    map_frame: map
    base_frame: base_link
    lidar_frame: laser

    filtered_lidar_topic: scan/road_env
    fov_topic: visualization/fov
    lidar_topic: scan
    obstacles_topic: visualization/obstacles
    
    environment_boundary: [0., 0., 2., 0., 2., -1.5, 0., -1.5]  # CW convex polygon [x1, y1, x2, y2, ...]
    road_rotation: 0.
    road_translation: [0.0, 0.0]
    
    ego_vehicle_size: [0.3, 0.18, 0.12]
    go_vehicle_offset: [0., 0., 0.06]
    # road_xml: /home/christiaan/thesis/robot_ws/install/foresee_the_unseen/share/foresee_the_unseen/resource/road_structure.xml

