/**:
  odom_node:
    ros__parameters:
      odom_frame: odom
      base_frame: base_link
      odometry_topic: odometry/wheel_encoders
      odometry_queue_size: 5 # (int)
      encoder_queue_size: 1 # (int)
      encoder_topic: wheel_encoders
      # do_broadcast_transform: True  # this is set in the launch file

      # Amount of seconds to use previous updates of the wheel encoders to calculate the velocity and position(encoders update freq = 50 Hz)
      max_history_time: 0.08  # [s]
