odom_node:
    ros__parameters:
        odom_frame: "odom"
        base_frame: "base_link"
        odometry_topic: "odom"
        odometry_queue_size: 5 # int
        encoder_queue_size: 1 # int
        left_encoder_topic: "left_wheel"
        right_encoder_topic: "right_wheel"

        # Wheel radius and base are tuned after measuring
        wheel_radius: 0.033 # [m] double
        ticks_per_rev: 1920. # double
        wheel_base: 0.145 # [m] double 

        do_broadcast_transform: true # set this in the launch file
        pose_variances: [0.0001, 0.0001, 0.0001, 0.0001, 0.0001, 0.0001]
        twist_variances: [0.0001, 0.0001, 0.0001, 0.0001, 0.0001, 0.0001]

