/**:
  trajectory_follower_node:
    ros__parameters:
      map_frame: map
      planner_frame: planner
      odom_frame: odom

      odom_topic: odometry/filtered
      trajectory_topic: trajectory
      motor_command_topic: cmd_motor
      trajectory_marker_topic: visualization/trajectory

      control_mode: velocity # `velocity` or `acceleration`

      do_visualize_trajectory: True
      do_store_data: False
      log_directory: /home/ubuntu/trajectory_log_files

      control_frequency: 20.0  # frequency of the motor controls send to the motor [Hz] (double)
      velocity_p: 5.  # proportional constant for the speed (double)
      steering_k: 0.3  # steering control gain (double)

      do_limit_acceleration: True
      max_acceleration: 0.5  # [m/s^2] Can be chosen
      max_velocity: 0.7  # [m/s] relates to the max acceleration (overapproximate)
      velocity_pwm_rate: 0.6  # 1 pmw == 0.6 m/s -> full speed (used for the acceleration mode)

      wheel_base_width: 0.145  # wheel base width [m] (double)
      wheel_base_length: 0.1  # wheel base length [m] (double)
      min_corner_radius: 0.25  # minimum corner radius [m]
      # max_steering_angle: 25.0 # max steering angle [deg] (double). Influences the minimum corner radius: r_min = wheel_base_length / tan(max_steering_angle)

