/imu_node:
  ros__parameters:
    base_frame: base_link
    imu_frame: imu_link
    imu_topic: imu_data

    update_frequency: 100.0
    use_magnetometer: true
    use_sim_time: false

    lin_acc_variances:  [0.5, 0.5, 0.5]
    ang_vel_variances:  [0.1, 0.1, 0.1]